In [1]:
import pandas as pd

In [2]:
!pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\raiss\appdata\local\programs\python\python312\lib\site-packages (3.1.3)
Requirement already satisfied: et-xmlfile in c:\users\raiss\appdata\local\programs\python\python312\lib\site-packages (from openpyxl) (1.1.0)

In [3]:
df = pd.read_excel('recursos_recebidos.xlsx')

In [4]:
df

,LOCALIDADE,POPULAÇÃO,TRANSFERÊNCIAS CONSTITUCIONAIS E LEGAIS,TRANSFERÊNCIAS ESPECÍFICAS E VOLUNTÁRIAS,GASTOS DIRETOS,BENEFÍCIOS AOS CIDADÃOS
0,BRASÍLIA - DF,2570160,"R$ 125.698.789,06","R$ 19.881.330.062,84","R$ 429.119.445,21","R$ 394.926.803,33"
1,CURITIBA - PR,1751907,"R$ 958.955.832,00","R$ 263.912.957,33","R$ 695.042.874,67","R$ 199.807.978,00"
2,RECIFE - PE,1537704,"R$ 955.028.523,80","R$ 398.814.087,46","R$ 556.214.436,34","R$ 511.393.918,72"
3,BELO HORIZONTE - MG,2375151,"R$ 1.695.197.250,91","R$ 389.667.347,38","R$ 1.305.529.903,53","R$ 350.047.092,69"
4,RIO DE JANEIRO - RJ,6320446,"R$ 2.527.783.799,22","R$ 570.729.586,23","R$ 1.957.054.212,99","R$ 946.482.128,86"
5,FORTALEZA - CE,2452185,"R$ 1.503.269.245,85","R$ 723.908.332,31","R$ 779.360.913,54","R$ 677.107.161,26"
6,SALVADOR - BA,2675656,"R$ 1.265.245.319,51","R$ 571.836.707,67","R$ 693.408.611,84","R$ 539.016.503,47"
7,SÃO PAULO - SP,11253503,"R$ 3.309.385.927,72","R$ 447.208.013,58","R$ 2.862.177.914,14","R$ 1.494.099.580,98"
8,MANAUS - AM,1802014,"R$ 781.951.503,09","R$ 458.221.006,95","R$ 323.730.496,14","R$ 459.554.689,37"
9,SÃO JOÃO DA BARRA - RJ,32747,"R$ 131.701.786,55","R$ 123.564.599,72","R$ 8.137.186,83","R$ 12.921.404,87"
10,ARRAIAL DO CABO - RJ,27715,"R$ 175.694.939,00","R$ 170.350.051,19","R$ 5.344.887,81","R$ 7.523.888,31"
11,MARABÁ - PA,233669,"R$ 173.375.483,50","R$ 125.973.694,55","R$ 47.401.788,95","R$ 53.440.193,34"
12,DUQUE DE CAXIAS - RJ,855048,"R$ 480.470.235,43","R$ 116.858.582,81","R$ 363.611.652,62","R$ 188.005.918,51"
13,CAMPO GRANDE - MS,786797,"R$ 526.325.888,51","R$ 156.670.754,92","R$ 369.655.133,59","R$ 204.853.987,18"
14,ANGRA DOS REIS - RJ,169511,"R$ 221.019.502,05","R$ 120.543.393,32","R$ 100.476.108,73","R$ 26.043.255,55"
15,ILHABELA - SP,28196,"R$ 148.058.175,96","R$ 140.742.270,11","R$ 7.315.905,85","R$ 4.726.035,84"
16,PORTO ALEGRE - RS,1409351,"R$ 836.555.861,76","R$ 162.911.826,00","R$ 673.644.035,76","R$ 203.591.992,32"
17,VITÓRIA - ES,327801,"R$ 213.401.885,78","R$ 125.664.849,44","R$ 87.737.036,34","R$ 53.937.533,22"
18,RIO DAS OSTRAS - RJ,105676,"R$ 136.160.888,37","R$ 121.078.780,15","R$ 15.082.108,22","R$ 18.871.659,42"

In [5]:
df.loc[9]

LOCALIDADE                                  SÃO JOÃO DA BARRA - RJ
POPULAÇÃO                                                    32747
TRANSFERÊNCIAS CONSTITUCIONAIS E LEGAIS          R$ 131.701.786,55
TRANSFERÊNCIAS ESPECÍFICAS E VOLUNTÁRIAS         R$ 123.564.599,72
GASTOS DIRETOS                                     R$ 8.137.186,83
BENEFÍCIOS AOS CIDADÃOS                           R$ 12.921.404,87
Name: 9, dtype: object

In [6]:
auxiliar = df.loc[9]

In [7]:
auxiliar

LOCALIDADE                                  SÃO JOÃO DA BARRA - RJ
POPULAÇÃO                                                    32747
TRANSFERÊNCIAS CONSTITUCIONAIS E LEGAIS          R$ 131.701.786,55
TRANSFERÊNCIAS ESPECÍFICAS E VOLUNTÁRIAS         R$ 123.564.599,72
GASTOS DIRETOS                                     R$ 8.137.186,83
BENEFÍCIOS AOS CIDADÃOS                           R$ 12.921.404,87
Name: 9, dtype: object

In [8]:
def limpa_valor(linha):
    linha['GASTOS DIRETOS'] = linha['GASTOS DIRETOS'].replace('R$ ', '')
    linha['GASTOS DIRETOS'] = linha['GASTOS DIRETOS'].replace('.', '')
    linha['GASTOS DIRETOS'] = linha['GASTOS DIRETOS'].replace(',', '')
    return linha

In [9]:
limpa_valor(auxiliar)

C:\Users\raiss\AppData\Local\Temp\ipykernel_17308\1515148543.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  linha['GASTOS DIRETOS'] = linha['GASTOS DIRETOS'].replace('R$ ', '')
C:\Users\raiss\AppData\Local\Temp\ipykernel_17308\1515148543.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  linha['GASTOS DIRETOS'] = linha['GASTOS DIRETOS'].replace('.', '')
C:\Users\raiss\AppData\Local\Temp\ipykernel_17308\1515148543.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  linha['GASTOS DIRETOS'] = linha['GASTOS DIRETOS'].replace(',', '')

LOCALIDADE                                  SÃO JOÃO DA BARRA - RJ
POPULAÇÃO                                                    32747
TRANSFERÊNCIAS CONSTITUCIONAIS E LEGAIS          R$ 131.701.786,55
TRANSFERÊNCIAS ESPECÍFICAS E VOLUNTÁRIAS         R$ 123.564.599,72
GASTOS DIRETOS                                           813718683
BENEFÍCIOS AOS CIDADÃOS                           R$ 12.921.404,87
Name: 9, dtype: object

In [10]:
def limpa_valor(linha):
    linha['GASTOS DIRETOS'] = linha['GASTOS DIRETOS'].replace('R$ ', '')
    linha['GASTOS DIRETOS'] = linha['GASTOS DIRETOS'].replace('.', '')
    linha['GASTOS DIRETOS'] = linha['GASTOS DIRETOS'].replace(',', '')
    valores = int(linha['GASTOS DIRETOS'])
    linha['GASTOS DIRETOS'] = valores
    return linha

In [11]:
auxiliar

LOCALIDADE                                  SÃO JOÃO DA BARRA - RJ
POPULAÇÃO                                                    32747
TRANSFERÊNCIAS CONSTITUCIONAIS E LEGAIS          R$ 131.701.786,55
TRANSFERÊNCIAS ESPECÍFICAS E VOLUNTÁRIAS         R$ 123.564.599,72
GASTOS DIRETOS                                           813718683
BENEFÍCIOS AOS CIDADÃOS                           R$ 12.921.404,87
Name: 9, dtype: object

In [12]:
df.apply(lambda x: limpa_valor(x), axis=1)

,LOCALIDADE,POPULAÇÃO,TRANSFERÊNCIAS CONSTITUCIONAIS E LEGAIS,TRANSFERÊNCIAS ESPECÍFICAS E VOLUNTÁRIAS,GASTOS DIRETOS,BENEFÍCIOS AOS CIDADÃOS
0,BRASÍLIA - DF,2570160,"R$ 125.698.789,06","R$ 19.881.330.062,84",42911944521,"R$ 394.926.803,33"
1,CURITIBA - PR,1751907,"R$ 958.955.832,00","R$ 263.912.957,33",69504287467,"R$ 199.807.978,00"
2,RECIFE - PE,1537704,"R$ 955.028.523,80","R$ 398.814.087,46",55621443634,"R$ 511.393.918,72"
3,BELO HORIZONTE - MG,2375151,"R$ 1.695.197.250,91","R$ 389.667.347,38",130552990353,"R$ 350.047.092,69"
4,RIO DE JANEIRO - RJ,6320446,"R$ 2.527.783.799,22","R$ 570.729.586,23",195705421299,"R$ 946.482.128,86"
5,FORTALEZA - CE,2452185,"R$ 1.503.269.245,85","R$ 723.908.332,31",77936091354,"R$ 677.107.161,26"
6,SALVADOR - BA,2675656,"R$ 1.265.245.319,51","R$ 571.836.707,67",69340861184,"R$ 539.016.503,47"
7,SÃO PAULO - SP,11253503,"R$ 3.309.385.927,72","R$ 447.208.013,58",286217791414,"R$ 1.494.099.580,98"
8,MANAUS - AM,1802014,"R$ 781.951.503,09","R$ 458.221.006,95",32373049614,"R$ 459.554.689,37"
9,SÃO JOÃO DA BARRA - RJ,32747,"R$ 131.701.786,55","R$ 123.564.599,72",813718683,"R$ 12.921.404,87"
10,ARRAIAL DO CABO - RJ,27715,"R$ 175.694.939,00","R$ 170.350.051,19",534488781,"R$ 7.523.888,31"
11,MARABÁ - PA,233669,"R$ 173.375.483,50","R$ 125.973.694,55",4740178895,"R$ 53.440.193,34"
12,DUQUE DE CAXIAS - RJ,855048,"R$ 480.470.235,43","R$ 116.858.582,81",36361165262,"R$ 188.005.918,51"
13,CAMPO GRANDE - MS,786797,"R$ 526.325.888,51","R$ 156.670.754,92",36965513359,"R$ 204.853.987,18"
14,ANGRA DOS REIS - RJ,169511,"R$ 221.019.502,05","R$ 120.543.393,32",10047610873,"R$ 26.043.255,55"
15,ILHABELA - SP,28196,"R$ 148.058.175,96","R$ 140.742.270,11",731590585,"R$ 4.726.035,84"
16,PORTO ALEGRE - RS,1409351,"R$ 836.555.861,76","R$ 162.911.826,00",67364403576,"R$ 203.591.992,32"
17,VITÓRIA - ES,327801,"R$ 213.401.885,78","R$ 125.664.849,44",8773703634,"R$ 53.937.533,22"
18,RIO DAS OSTRAS - RJ,105676,"R$ 136.160.888,37","R$ 121.078.780,15",1508210822,"R$ 18.871.659,42"